openapi: 3.0.0
info:
  title: One Day Planner API
  contact: {}
  version: '1.0'
servers:
  - url: http://localhost:8000/api/v1
    variables: {}
paths:
  /plans:
    get:
      tags:
        - Plans
      summary: Get All Plans or by category with pagination set by default to 10
      operationId: GetAllPlans
      parameters:
        - in: query
          name: categoryId
          schema:
            type: string
            example: nature-and-history
          required: false
          description: Category ID to filter plans by category (optional)
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          required: false
          description: Page number for pagination (optional, default is 1)
        - in: query
          name: size
          schema:
            type: integer
            default: 10
          required: false
          description: Number of items per page for pagination (optional, default is 10)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: |
                {
                  "categoryId": "city-exploration",
                  "page": 1,
                  "size": 10,
                  "items": [
                    {
                      "planId": "san-francisco-day-tour",
                      "title": "San Francisco Day Tour",
                      "description": "A one-day tour exploring San Francisco's iconic sites, parks, museums, and dining establishments.",
                      "images": [
                        "https://dummyimage.com/390x265/2196F3/fff.png",
                        "https://dummyimage.com/390x265/FF9800/fff.png"
                      ],
                      "type": "Full day",
                      "stopCount": 5,
                      "rating": 4.8,
                      "reviewCount": 120,
                      "startLocation": [37.7955, -122.3937],
                      "finishLocation": [37.7879, -122.4074],
                      "distance": 5,
                      "duration": "8 hours",
                      "userId": "jane-doe",
                      "categoryId": "city-exploration",
                      "createdAt": "2025-04-04T16:50:54Z",
                      "updatedAt": "2025-04-04T16:50:54Z"
                    }
                  ]
                }
          headers: {}
      deprecated: false
  /plans/plan/{planId}:
    parameters:
      - in: path
        name: planId
        schema:
          type: string
          example: san-francisco-day-tour
        required: true
        description: The plan ID
    get:
      tags:
        - Plans
      summary: Get Single Plan
      operationId: GetPlan
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: |
                {
                  "planId": "san-francisco-day-tour",
                  "title": "San Francisco Day Tour",
                  "description": "A one-day tour exploring San Francisco's iconic sites, parks, museums, and dining establishments.",
                  "images": ["https://dummyimage.com/390x265/2196F3/fff.png"],
                  "type": "Full day",
                  "stopCount": 1,
                  "rating": 4.8,
                  "reviewCount": 120,
                  "startLocation": [37.7955, -122.3937],
                  "finishLocation": [37.7879, -122.4074],
                  "distance": 5,
                  "duration": "8 hours",
                  "userId": "jane-doe",
                  "categoryId": "city-exploration",
                  "createdAt": "2025-04-04T16:50:54Z",
                  "updatedAt": "2025-04-04T16:50:54Z",
                  "stops": [
                    {
                        "stopId": "stop-001",
                        "planId": "san-francisco-day-tour",
                        "name": "Ferry Building Marketplace",
                        "imageURL": "https://dummyimage.com/390x265/2196F3/fff.png",
                        "address": "1 Ferry Building, San Francisco, CA 94111",
                        "description": "A historic building offering a variety of food vendors, shops, and a farmers market.",
                        "location": [37.7955, -122.3937],
                        "sequence": 1,
                        "createdAt": "2025-04-04T16:50:54Z",
                        "updatedAt": "2025-04-04T16:50:54Z"
                    }
                  ]
                }
          headers: {}
      deprecated: false
  /plans/user/{userId}:
    parameters:
      - in: path
        name: userId
        schema:
          type: string
          example: alice-johnson
        required: true
        description: The user ID
    get:
      tags:
        - Plans
      summary: Get user's details and their plans
      operationId: GetUserPlans
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: |
                {
                  "userId": "alice-johnson",
                  "name": "Alice Johnson",
                  "email": "alice.johnson@example.com",
                  "pictureURL": "https://api.dicebear.com/9.x/dylan/svg?seed=alice-johnson",
                  "createdAt": "2025-04-04T17:00:54Z",
                  "updatedAt": "2025-04-04T17:00:54Z",
                  "plans": {
                    "page": 1,
                    "size": 10,
                    "items": [
                      {
                        "planId": "berkeley-highlights-tour",
                        "title": "Berkeley Highlights Tour",
                        "description": "A day exploring the University of California, Berkeley campus and surrounding cultural spots.",
                        "images": ["https://dummyimage.com/390x265/673AB7/fff.png"],
                        "type": "Evening",
                        "stopCount": 4,
                        "rating": 4.9,
                        "reviewCount": 95,
                        "startLocation": [37.8719, -122.2585],
                        "finishLocation": [37.8793, -122.2698],
                        "distance": 3,
                        "duration": "6 hours",
                        "userId": "alice-johnson",
                        "categoryId": "academic-and-cultural-tour",
                        "createdAt": "2025-04-04T17:00:54Z",
                        "updatedAt": "2025-04-04T17:00:54Z"
                      }
                    ]
                  }
                }
          headers: {}
      deprecated: false
  /plans/category/{categoryId}:
    parameters:
      - in: path
        name: categoryId
        schema:
          type: string
          example: nature-and-history
        required: true
        description: The category ID
    get:
      tags:
        - Plans
      summary: Get a category's details and its plans
      operationId: GetCategoryPlans
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: |
                {
                  "categoryId": "nature-and-history",
                  "name": "Nature and History",
                  "description": "Explore Berkeley's parks, history, and natural beauty.",
                  "imageURL": "https://dummyimage.com/1050x230/8BC34A/fff.png",
                  "createdAt": "2025-04-04T17:00:54Z",
                  "updatedAt": "2025-04-04T17:00:54Z",
                  "plans": {
                    "page": 1,
                    "size": 10,
                    "items": [
                      {
                        "planId": "berkeley-nature-history-tour",
                        "title": "Berkeley Nature & History Tour",
                        "description": "A day exploring Berkeley's natural beauty, parks, and historical sites.",
                        "images": ["https://dummyimage.com/390x265/8BC34A/fff.png"],
                        "type": "Night",
                        "stopCount": 5,
                        "rating": 4.8,
                        "reviewCount": 62,
                        "startLocation": [37.8747, -122.2627],
                        "finishLocation": [37.8712, -122.3021],
                        "distance": 5.5,
                        "duration": "7 hours",
                        "userId": "alice-johnson",
                        "categoryId": "nature-and-history",
                        "createdAt": "2025-04-04T17:00:54Z",
                        "updatedAt": "2025-04-04T17:00:54Z"
                      }
                    ]
                  }
                }
          headers: {}
      deprecated: false
security:
  - httpBearer: []
tags:
  - name: Plans
    description: ''